name: CI

on:
  - pull_request

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 
          cache: yarn

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build 
        run: yarn build 

      - name: Test
        run: yarn node --experimental-vm-modules $(yarn bin jest)
