name: Release

on:
  push:
    branches:
      - main 

jobs:
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: release package(s)'
          title: 'chore: release package(s)'
          version: yarn version
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
