name: Release

on:
  push:
    branches:
      - main 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          # Enable Trusted Publishing
          always-auth: true
      - name: Build
        uses: ./.github/workflows/build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: release package(s)'
          title: 'chore: release package(s)'
          version: yarn version
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}