name: Release

on:
  push:
    branches:
      - main 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        uses: ./.github/workflows/build
      - name: Publish to npm
        run: npm publish